app = "enigme-bot"
primary_region = "cdg" # Paris (Charles de Gaulle)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[mounts]
  source = "enigme_data"
  destination = "/app/data"

[processes]
  app = "npm start"
